### ISSUE TITLE
Reloadability of grammars

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#385] opened 2019-02-12 02:19 UTC
> From @synkarius Reloadability is achievable without text files. Ultimately the text files should go away. In order to achieve better reloadability, we ought to be actually managing modules via `importlib` and watching directories for file changes, possibly with fallback to previously loaded modules if the changed files have errors.

**Comment by LexiconCode** [comment] 2019-02-12 02:25
In regards to testing grammars for errors and unit tests @Danesprite has been on a method for dragonfly.[cli](https://dragonfly2.readthedocs.io/en/latest/cli.html) framework for testing grammars.

**Comment by synkarius** [comment] 2019-02-14 16:50
I noticed that he had added that. That is really a great contribution, and should making unit testing both Dragonfly and Caster much easier.

**Comment by Danesprite** [comment] 2019-02-15 04:05
@synkarius Thanks! :)

I think it makes some sense to use the `dragonfly test` command as a sort of staging area for changes to grammars. That way the only errors that might get through are engine-specific, e.g. grammar complexity errors. Using the command with a file watcher would make that easier of course.

**Comment by Danesprite** [comment] 2019-03-19 11:50
I was wondering if a ``changeCallback`` function in *_caster.py* would be a good idea for this instead of watching for file changes. If the function exists in a command module, natlink calls it on a mic state change. The function could be used to make this work like reloading modules in the *MacroSystem* folder.

```Python
def changeCallback(cbType, args):
    print(cbType, args)

```

**Comment by alexboche** [comment] 2019-06-05 01:37
Along with reloadability it would be good to add a feature where when you reload, if the current grammar breaks (e.g. if there's a syntax error), then caster just reverts to the most recently working grammar. I think that was implemented in this system https://voca.readthedocs.io/en/latest/readme.html#features

**Comment by alexboche** [comment] 2019-06-18 08:18
Just copying @roccah 's from the dragonfly channel which is relevant to this issue.
>Reloading modules can be done with various levels of completeness. 1) importlib.reload() or imp.reload() update the code that lives at module scope in the reloaded module. Already-existing objects created from the previous version will not be affected. Also, old module variables won't be deleted. 2) superreload() rewrites the old functions, methods, and classes, and clears the module namespace. 3) Using a separate process. This means there is no shared memory and holding old or inconsistent values is not an issue, but data must be sent between each process explicitly. Each of these strategies is about reloading python modules. Then there's reloading grammars. Grammars are compiled and sent into Dragon when Dragonfly starts. To reload a grammar, it is necessary to reload the module defining the grammar, compile that grammar, remove the previous grammar from Dragon, and load the new grammar into Dragon. Currently, Caster is designed so that each module that defines grammars also loads those grammars into Dragon. An alternative architecture, which you can see in my demo [here](https://github.com/python-voca/voca), is having each module define grammars but not connect to the speech engine--instead managing the active grammars from inside the main() function.

**Comment by alexboche** [comment] 2019-06-26 11:04
@synkarius  From an email with the dragonfly user named Hawkeye Parker a while back (maybe of some relevance):

>I don't know the details, but the things you friend mentioned -- …problems with global state -- these _are_ common problems in many code bases. For Dragonfly in general (and Natlink), having to restart Dragon to reload things is a problem. For dragonfly, toggling the Dragon microphone off/on usually works, but I actually have a script for reloading all of my Dragonfly grammars:
```
def reloadAll():
    print "Reloading everything in the Macrosystem directory..."
    user_directory_files = [f for f in os.listdir(MACROSYSTEM_DIRECTORY) if f.endswith('.py')]
    for file in user_directory_files:
        utils.touch(MACROSYSTEM_DIRECTORY + "\\" + file)
    utils.toggleMicrophone()
```
>In case it's helpful, all of the source is in https://github.com/haughki/MyDragonflyModules (I'm guessing it's https://github.com/haughki/MyDragonflyModules/blob/master/_reloader.py) -- you can see how I did everything there. Something tells me that this wouldn't work with Caster, but I don't know for sure.

**Comment by synkarius** [comment] 2019-06-28 04:31
Thank you @alexboche. That is helpful. :)

After speaking w/ @LexiconCode about this feature, I think I am going to rewrite the CCR Merger along with / in order to do this. The CCR Merger a train wreck in its current state, difficult to modify difficult to test (and I wrote the damn thing...). The responsibility of managing grammars and in-memory rules needs to be extracted from it. @lexxish mentioned a "Grammar Registry" in some other issue, and I think I objected at first, but I've come around and am liking the idea.

**Comment by roccah** [comment] 2019-06-28 07:01
I have a couple thoughts on the architecture of this section. In general, my preference is:

- Grammars are defined statelessly in each grammar module, in separate registries, one per module.

  https://github.com/python-voca/voca/blob/ba5cda6f0f46430329c379eafd8203b250249f69/src/voca/plugins/python.py#L9-L29

- They are *not* injected into the engine from this point; the grammar modules do not have any reference to the engine or nexus. 
- Somewhere near the top of the program, perhaps `main()`, we connect to the engine, and hold the reference to the connection object internally inside of `main()`. There is no process-global connection object.
- Also near the top of the program, we collect a list of grammar registries to load. We can iterate over these modules, collect the `registry` value from each one, and merge them.


In a single-process implementation, it could look something like:

```python3
import types
import typing as t
import importlib
import sys

# These would need to be defined.
from ... import (
    handle_command,
    backends,
    combine_registries,
    ReloadAll,
    Backend,
    Registry,
    find_modules
)


def get_registries() -> t.List[Registry]:
    modules: t.List[types.ModuleType] = []
    for import_path in find_modules():
        if import_path in sys.modules.keys():
            module = importlib.reload(import_path)
        else:
            module = importlib.import_module(import_path)
        modules.append(module)

    return [module.registry for module in modules]



def main(backend_name: str):
    backend_class: t.Type[Backend] = getattr(backends, backend_name)
    backend: Backend = backend_class()
    backend.connect()

    registries: t.List[Registry] = get_registries()
    combined_registry: Registry = combine_registries(registries)
    backend.load(combined_registry.grammar)

    while True:
        command: str = backend.receive_command()
        try:
            handle_command(command)
        except ReloadAll:
            backend.unload_all()

            registries: t.List[Registry] = get_registries()
            combined_registry: Registry = combine_registries(registries)
            backend.load(combined_registry.grammar)

```

**Comment by daanzu** [comment] 2019-06-28 11:20
I think a declarative or registry approach is a good idea. So, when a module is loaded, it constructs a grammar and then submits it to Caster. Then Caster can process it, and hopefully keep track of where everything came from.

Where is the problematic global state coming from currently? The CCRMerger itself? It'd be interesting to make a list.

**Comment by synkarius** [comment] 2019-07-03 05:04
Thank you @alexboche. That is helpful. :)

**Comment by synkarius** [comment] 2019-07-03 05:07
@daanzu I think I was against the idea of a registry in some other issue, but I've come around and I agree that it is a good idea. I'm going to go with it for this feature. As for problematic global state, there is a lot of that, but with regards to this feature, it's mostly in the CCR Merger itself, yes. I am rewriting the CCR Merger as a part of this change so that it doesn't have this problem.

**Comment by synkarius** [comment] 2019-07-25 04:31
This is taking longer than I expected, but there are only a few things left to do, none of which are daunting:
* finish fixing the selfmod rules (3.5/5 of them are complete)
* write notes on what has changed
* finish new ccrmerger implementation, incl contexted CCR rules
* don't force the user to identify the module paths themselves
* general user testing
* unit tests (I will create a PR before writing these so the community can start testing, and another PR after they are done)

**Comment by lexxish** [comment] 2019-07-31 15:50
Will this support reloading rules that depend on other python modules? For example ChromeRule.py currently depends on BrowserSharedCommands.py.

**Comment by synkarius** [comment] 2019-08-01 01:44
@lexxish Rules which depend on other modules will be reloadable yes, but their dependencies will not be reloaded. In your example, if you change ChromeRule.py, it will reload. If you change BrowserSharedCommands.py, nothing will reload. If you change BrowserSharedCommands.py and then ChromeRule.py, ChromeRule.py will reload but with the old version of BrowserSharedCommands.py. This "simple" version of module reloading should be able to be upgraded with far less work than what I'm doing now, in the future. 

For clarity, I am rewriting a significant chunk of Caster, but not the whole thing top to bottom.

As for `R`, I agree that it would be nicer to be able to do without it. I am not going to get rid of it as a part of this rewrite, but if anyone is interested, this is what needs to be replaced:
- It adds metadata to actions. I had grander dreams of what I wanted to do with this metadata once in terms of GUI windows/components, but clearly that never really happened. So the usefulness of that metadata is somewhat questionable now.
- It enables ContextSeeker and AsynchronousAction. ContextSeeker was ultimately too complicated and never got used much _except_ by AsynchronousAction, which simplified it somewhat and I _think_ is generally useful.

**Comment by lexxish** [comment] 2019-08-04 22:40
A couple more comments on the merger and rule management. I think rule loading should be moved to a single bootstrap file rather than having each rule load itself. Similarly, the definition of core rules (`CORE = ["alphabet", "navigation", "numbers", "punctuation"]`) should be defined outside of the CCR merger. This will allow you to clearly see all the rules being loaded and how they are configured. Lastly, I've found that rules that work fine as DragonFluid rules cause complexity errors when converted to merge rules. Is this because DragonFluid rules mimics chained commands (https://dragonfluid.readthedocs.io/en/latest/Concepts.html#translation) or is there some other reason?

**Comment by lexxish** [comment] 2019-08-07 18:06
@synkarius I narrowed most of the complexity errors down to rules like "find [character1][character2][character3][character4]". I think @alexboche ran into a similar issue in the past. Alex did you ever find a solution for this?

Also ran into complexity issues with high (but I think realistic) max n values.

With DragonFluid rules I was using a hierarchy of rules to allow overriding of commands based on context so not sure how I will be able to switch back to MergeRules yet since this strategy creates some pretty complex rules.

**Comment by daanzu** [comment] 2019-08-08 05:54
@lexxish The natlink & Kaldi backends take advantage of `Repetition` `optimize` (default `True`) parameter to ignore the `min` & `max` and instead use a loop to simplify. This can also help with rules like you mentioned. I wrote an example that I think fixed it for @alexboche .

```
mapping = {"(go | move) <direction> [<before_after>] [<number_of_lines_to_search>] [<occurrence_number>] <character_sequence>":
    Function(text_manipulation_functions.move_until_phrase, dict(character_sequence="phrase"))}
character_dict = {"arch": "a", "brov": "b", "char": "c", "delta": "d"}
character_choice_object = Choice("character_choice", character_dict)
extras = [ Repetition(character_choice_object, min=2, min=3, name="character_sequence"), ]
```

**Comment by lexxish** [comment] 2019-08-12 15:22
@daanzu this helped but did not solve the issue. I was able to create several more commands when using a Repetition, but still hit a complexity limit faster than QuickFluidRules. I looked into the code more and I don't think there is an easy fix. I believe the difference stems from how QuickFluidRules handle parsing at runtime and MergeRules handle parsing at boot time and I don't see an easy way to fix this in the code (@synkarius please correct me if I'm wrong).

I did not have a good understanding of this complexity issue when I wrote https://github.com/dictation-toolbox/Caster/issues/576. With this in mind it the benefits to QuickFluidRules outweighs the drawbacks for me personally. However, I believe the ideal would actually be to combine the features of both. This could be a new issue, but I wanted to see how others felt about merging the functionality and allowing the option to parse/merge rules at runtime.

**QuickFluidRules:**
+extremely hard to hit complexity limits (I've never done so)
-can't handle rules that start with extras (something I'd like to fix in the future)
-fewer features (although the most common use case is covered)

**MergeRules:**
+has several advanced features that are interesting but not frequently used (perhaps they will be leveraged more in the future though)
+can handle rules that start with extras (limited benefit due to hitting complexity limits)
-relatively easy to hit complexity limits

**Comment by synkarius** [comment] 2019-08-14 12:20
@lexxish IIRC, the DragonFluid project doesn't hit complexity limits because it's basically all free dictation which is then parsed by Python rather than Dragon, right? It's been years since I looked at it and I can't remember well. IOW, Dragonfluid basically only has one rule as far as Dragon is concerned?

**Comment by synkarius** [comment] 2019-08-14 14:00
Yeah, I am remembering correctly.
https://dragonfluid.readthedocs.io/en/latest/Suitability.html#suitability

Don't forget to add to the list of cons for QuickFluidRules that only the first command in the chain gets the "recognition boost" and that recognition for all other commands in a single utterance will only be as accurate as free dictation is.

I'm not saying it's not worth using. But that is a major drawback IMO.

**Comment by lexxish** [comment] 2019-08-14 18:39
> @lexxish IIRC, the DragonFluid project doesn't hit complexity limits because it's basically all free dictation which is then parsed by Python rather than Dragon, right? It's been years since I looked at it and I can't remember well. IOW, Dragonfluid basically only has one rule as far as Dragon is concerned?

Not sure if it's only one rule in all cases, but my understanding is that the merging itself is happening in python during execution of the commands. This wouldn't really have any benefit if it weren't for Dragons complexity limits. Perhaps some startup time improvements but likely negligible for most use cases.

**Comment by synkarius** [comment] 2019-08-15 02:57
Yeah, I think "one rule (under the hood)" was an overstatement on my part. But that's the gist of it, from that ReadTheDocs page. Let's say you have 3 commands with specs one word each, we'll call them A, B, and C. _With_ the "recognition boost", below they'll be denoted A, B, C. _Without the recognition boost_, they'll be denoted as lowercase, to show that they're being recognized by the engine as free dictation, then parsed into commands by Dragonfluid. You could have CCR chains like:
```
A a a a a a a a a a
A b c
B c c c a b a c a 
B
C c a b c a a b c a b b a c b a c
```
However, you couldn't, for example, have:
```
A B C
B C C C A B A C A
```
You're basically making a tradeoff: higher complexity or higher accuracy. At least that's my reading of that document. I could be wrong.

I can definitely see use cases for using Dragonfluid. For example, perhaps you're doing medical dictation and you know that someone else will transcribe your notes later. Or maybe you're using voice to play a game and a few mis-clicks don't make much of a difference.

Incidentally, it wouldn't be too hard to implement this in Caster if you wanted it there. You'd just have to create a command with a free dictation element which resulted in a Playback Dragonfly action of all the words captured in free dictation.

**Comment by synkarius** [comment] 2019-08-30 04:27
There are four remaining known issues which I need to take care of:

1. sikuli profile reloading issue, originally resolved by @seekM -- need to put the solution back in such that it works with the new system
2. "TransformersActivationRule", "GrammarActivatorRule", "HooksActivationRule",  keep getting added to activated_rules.toml even if they're already in there
3. LegionGridRule, etc, should be added to default-on ("core") rules, also HMC rules
4. Need a new concept of "activated" vs "enabled" to speed up boot time -- as the number of rules keeps growing, so does the amount to load at boot time. Will put in a system where the user can whitelist or blacklist rules such that Caster only loads the "enabled" set instead of all rules. The loaded rules can then be activated/deactivated like it has been in classic Caster. The default set is up for debate.

**Comment by synkarius** [comment] 2019-08-30 04:29
Admittedly, (4) is beyond the scope of #385, but it won't be hard so I may as well just roll it in with all the other new changes.

**Comment by LexiconCode** [comment] 2019-09-01 00:17
@synkarius this was originally intended to detect a profile change within Dragon. Then https://github.com/dictation-toolbox/Caster/pull/511 and https://github.com/dictation-toolbox/Caster/pull/472


```
# if globals().has_key('profile_switch_occurred'):
#     reload(sikulixx)
# else:
#     profile_switch_occurred = None
```

**Comment by daanzu** [comment] 2019-09-01 01:08
@synkarius FWIW, if Caster could build merge rules reproducibly, it would really help Kaldi backend. So for a given set of enabled grammars, if the merge rule constructor could always construct it in the same order, the file cache could avoid recompiling a grammar graph that is effectively the same but superficially different. I'm not sure there's a way to do it reliably inside the backend, depending on how Caster does it. Just mentioning it while it is being worked on.

**Comment by synkarius** [comment] 2019-09-02 14:02
@LexiconCode Thank you. Looking at those, I see what I need to do in order to restore that functionality.

@daanzu I think I understand what you're asking for, but there might be a kind of inherent problem in it. Let me explain via an example. Suppose you're a programmer working on a full stack web project. You want to be using three grammars: Navigation, Java, and Javascript. Navigation has no spec incompatibilities with either Java or Javascript, but both Java and Javscript have an "if else" spec and are therefore incompatible with each other. Therefore, they cannot both be active at the same time, at least not under the classic (and current) merge strategy. So what ends up happening is that as you work, you need to switch between having Navigation + Java or Navigation + Javascript. (In real life, I think people have more rules active than that, like the "core" set + an IDE + a language + maybe some other stuff, but for the sake of this example I'll keep it simple.)

(Also note here, that when I say you have multiple MergeRules active at once, what I really mean is that multiple MergeRules have been combined by the ccrmerger into a single RepeatRule and it is that RepeatRule and not the MergeRules which is submitted to the speech engine.)

So the "active" set of merged rules might look like:
```
A, B, C, D, F, K
then
A, B, C, D, K, G
then
A, B, C, D, K, F
```
Here, "G" and "F" would be like Java and Javascript in my earlier example: they are rules which are incompatible. Whichever is activated last gets merged last. But what I'm wondering is, does Kaldi really care about how the rules are constructed, or does it only care about the content of the composite RepeatRule? I would guess the latter. In that case, [A, B, C, D, F, K] and [A, B, C, D, K, F] are really the same rule, right? If I'm wrong about that, there are some minor optimizations I can make, for example to ensure that you always do the rule construction in a deterministic way, but I doubt that that part matters since it's really just constructing an unordered hashmap out of smaller unordered hashmaps.

**Comment by synkarius** [comment] 2019-09-02 19:59
@daanzu I've been thinking about what you said a bit more today and it occurred to me that maybe you didn't mean the order of the MergeRules which go into the single CCR RepeatRule, but the order in which the single CCR rule and the non-CCR rules are submitted to the speech engine? That would be a much more tractable problem to deal with, so I'm kind of hoping it's that.

**Comment by daanzu** [comment] 2019-09-03 03:27
Thanks for the detailed reply! You are right that those two merge rules are semantically the same for Kaldi, but their syntactic difference does matter to my caching in the backend.

The Kaldi compilation process is entirely based on graphs. Constructing each grammar graph is fast, but then the compilation process performs three steps, each of which composes the previous graph with another graph (part of the model) and performs various graph optimizations. It is these steps that take time, on the order of 2-5s total for a large grammar like a CCRMergeRule. However, I have a cache for these compiled graphs, where I take the md5 hash of the textual description of the input grammar graph, and if it is the same as a previous one, I can reuse its output, skipping entire compilation process and loading in a fraction of a second.

The problem is this method of detection depends on syntactic equivalence and thus the elements occurring in exactly the same order. There's probably a way from me to detect the semantically-equivalent grammars in the backend instead, but that seems fragile and/or slow, and I wonder if it would be easier during grammar construction in Caster.

Unfortunately, I do mean the order of MergeRules in a CCRRepeatRule. The order of submitting rules/grammars to the engine does not matter, only the order of the elements in each rule.

**Comment by synkarius** [comment] 2019-09-04 03:36
> Unfortunately, I do mean the order of MergeRules in a CCRRepeatRule. The order of submitting rules/grammars to the engine does not matter, only the order of the elements in each rule.

That's interesting, and maybe very fortunate. It would be trivial to guarantee that any given set of rules merges in the same order every time. It's still the case that users are going to be switching rule combinations fairly frequently, and if I understand you correctly, even with my "deterministic merging" optimization, there would still be one long merge per rule combo, but at least then it would be only one long merge per combo instead of potentially several. 

I can include that optimization in this project. I'll add it to the list above.

**Comment by synkarius** [comment] 2019-09-04 03:37
Whoops, meant to tag you there, @daanzu.

**Comment by daanzu** [comment] 2019-09-04 08:44
@synkarius Great, that should be a big help! Yes, there will still be one will long pause for compilation for each new rule combo, but I figure there aren't that many combinations that people use frequently. Also, the cache persists between runs; it only needs to be regenerated when the model, lexicon, or the underlying grammars change. Other than that, Kaldi should be able to load any previous combination in milliseconds.

Oh, that's probably worth mentioning: it is helpful for the order to remain the same between runs, too, so the deterministic merging would hopefully use the rule names or something that doesn't change between runs.

**Comment by synkarius** [comment] 2019-09-05 01:44
@daanzu Yup, I was thinking of using rule names. :)

**Comment by synkarius** [comment] 2019-09-05 02:22
@daanzu 
https://github.com/synkarius/Caster/commit/f22caa3e948d9261a2554a5d3956581eb47c4754

If I'm understanding you correctly, I think that should do the trick? This is after all activated ccr rules have been merged but before the combined rule is submitted to the engine. Rather than alphabetizing rules by name, I figured I'd just swap out the normal MappingRule `dict` for an `OrderedDict` of the same commands, sorted by spec. Thoughts?

**Comment by daanzu** [comment] 2019-09-05 06:58
I don't know all the details of the Caster merging. So all the specs of all the rules get combined together into one giant mapping dict? It sounds like that should work then. Since the caching works by hashing everything anyway, it doesn't matter how different the stuff is, as long as each combination always appears the same.

**Comment by synkarius** [comment] 2019-09-05 22:45
@daanzu There's basically two kinds of rules that get submitted the the speech engine in Caster: the ones that get combined and the ones that don't. Obviously the ones the don't never change, so we don't need to worry about those. But yes, in the case of the ones that get combined, it all turns into one giant mapping dict.

Good then, hopefully that does the trick. This branch still isn't quite functional, but when it gets merged into `develop`, please do let me know if you see a difference. :)

**Comment by synkarius** [comment] 2019-09-08 03:14
# [Caster 1.0.0 Changes Summary](#caster-100-changes-summary)

1.  New Concepts
    1.  Transformers  

        See: base_transformer.py, gdef_transformer.py  

        In pre-1.0.0 Caster, there was a badly named feature called "filter functions". The idea of these "filter functions" was that Caster would define several times at which rules were being merged together, and would give the user access to make changes to the merged rules at these times. Due primarily to difficulty of use, "filter functions" did not get used much.  

        What "filter functions" ultimately sought to provide was a way for the user to change parts of Caster rules without needing to make changes to the source code, so that personal customizations wouldn't affect everyone else.  

        Transformers are a simplified, safer, and more descriptively named version of filter functions. Rather than providing the user with a pair of rules and a metadata object, transformers simply provide the user with a rule instance, with the intent that the user can then modify the rule instance and expect their modifications to be applied to whichever rules they've defined the transformer as being applicable to.  

        See also section 4A, "The fate of transformers" for comments on transformer vs user directory usage/applicability.
    2.  Hooks  

        See: base_hook.py, companion_rule_hook.py, printer_hook.py, base_event.py, rule_activation_event.py, node_change_event.py  

        Hooks are a new concept to Caster 1.0.0\. The basic idea is that Caster itself defines events, objects which contain immutable information about the stuff going on in the "guts" of Caster, and then those objects are fed to "hooks", user-defined listeners which can do whatever they want with said information. This should allow a decent amount of customization to happen without needing to make changes in the "guts" (Nexus, GrammarManager, CCRMerger, etc.) of Caster.  

        Loosely coupled code leads to less bugs and more productivity, and so the use of hooks rather than "guts" modifications is encouraged whenever possible.
    3.  Loaded vs Enabled  

        See: rules.toml  

        Pre-1.0.0 Caster loads all rules at boot and then allows the user to enable the rules they want. The number of Caster rules has grown immensely in the past few years, which is great, but means that the initial load time has grown as well.  

        In order to reduce boot time, new configuration has been added to allow the user to control which rules get loaded. Most users won't be using the majority of the total available rules, so it doesn't make sense to encumber most users with most of the rules.  

        New users will be provided a core set of rules to get started with and then expected to manage which rules load for them either in whitelist or blacklist mode.  

    4.  Unified Content Loading  

        The UserContentManager has been upgraded such that it now handles loading of all Caster content. This includes the rules (ccr and non-ccr, app, and self-mod), the transformers, and the hooks. This includes content that comes with Caster ("starter" content) and content that users create or modify in the user directory ("user" content).  

        If a user module has the same filename as a starter module, the user module will get priority. This means that you can overwrite Caster starter rules by just copying them into the user directory and changing them there.  

        Just as the UserContentManager required modules to have a function named "get_rule", now ALL content which is to be loaded requires such a function. The function names are "get_rule", "get_transformer", and "get_hook" respectively. See section 3C for rule design constraints imposed by this change.  

    5.  RuleDetails  

        Along the same lines as the unified loading mechanism, metadata about rules had to be provided by a common data structure which would work for both MergeRules and MappingRules. This was done via the RuleDetails object, which must always be provided in the "get_rule" function along with the rule class.  

2.  User Directory Changes  

    1.  Config File Changes  

        A bunch of the config files got changed or added. Some settings got removed because they were no longer necessary. The following is a list of config files which got changed somehow.  

        bringme.toml -> sm_bringme.toml  

        BringMe's config file got changed due to a larger change in how self modifying rules work. "Selfmod" rules used to store their state in memory. Now, when a ccr rule is enabled/disabled, all ccr rules, including selfmod rules, are instantiated anew. That means that selfmod rules can't store their state in memory anymore, so they all flush it out to disk now instead.  

        aliases.toml -> sm_aliases.toml, sm_chain_aliases.toml  

        The Alias rules got updated to flush out their state to disk in the same way that BringMe did.  

        ccr.toml -> rules.toml  

        The ccr config file underwent significant changes. Now in addition to tracking which rules are enabled (under "_enabled_ordered", which you should probably not mess with), and which rules load when Caster boots (under "whitelisted", which you definitely should mess with), but now it manages both ccr and non-ccr rules. ALL rules managed by Caster are tracked in this config file. In addition, there are a handful of rules which get special treatment by the GrammarManager: "internal" rules-- these are the rules which are generated by/for loaded content and which do not belong in the set of rules which can be reloaded. These rules are listed under "_internal", and you _can_ turn them off but it is strongly discouraged.  

        sm_history.toml  

        This is the config file where HistoryRule (another selfmod rule) dumps its state before reloading. Same reasons as BringMe.  

        transformers.toml  

        This new config file controls which transformers are active. It works the same way that the old ccr.toml config file did.  

        hooks.toml  

        This new config file controls which hooks are active. It works the same way that the old ccr.toml config file did.  

        companion_config.toml  

        This new config file controls which rules have companion rules. Companion rules are what was controlled by the "non" field on pre-1.0.0 MergeRules: rules that are automatically enabled and disabled when another rule is enabled/disabled. Since companion rules are now controlled via hooks, enabling/disabling the whole feature means disabling that particular hook. CAUTION: companion rules are a bit more powerful than "non"s-- one rule can have multiple companions instead of it being strictly one to one like it was before. But with great power comes great responsibility; if you get carried away with companion rules, it is completely possible to have a companion rule circle, which is to say, an infinite enable loop.  

        B. Directories  

        A few directories have also been added / changed.  

        <user_dir>/transformers  

        This replaces <user_dir>/filters. The same kind of overriding happens as with the rules.  

        <user_dir>/hooks  

        This is where user created hooks go. The same kind of overriding happens as with the rules.  

3.  Summary of the New System  

    1.  What the GrammarManager does at boot time  

        1.  Content Request Generation  

            When Caster starts up, the GrammarManager scans both the BASE_PATH and USER_DIR for python files which have "get_rule" ,"get_transformer", or "get_hook". The resulting list of files are added as "content requests".  

        2.  Request Processing  

            All requests are then sorted by type. Rule requests are filtered out if they are not marked as being whitelisted in rules.toml.  

            User content overrides starter content by module file name.  

            There are three layers of safety checks which occur during rule request processing: the module is test-imported, the module rule is test-instantiated, and if it is a ccr rule, various configuration validations are applied against it. If the rule fails any of these three checks, it will be rejected and skipped.  

        3.  Registration  

            At this point, the rule is considered to be safe for use. Its class and RuleDetails objects are stored in the GrammarManager. Note that only classes are stored, never instances.  

            The rule is then passed to the GrammarActivator, which makes the enable/disable commands for it. These enable/disable commands are generated on a best-guess basis. A ccr rule will have a pronunciation, but MappingRules should have a name at least, which can be used as the "trigger" word, as in "enable <trigger>".  

            The rule's file path is then passed to the Reload Observable. This is either a timer-based or command-based object which monitors all registered modules' file paths for changes, depending on how it is configured in settings.toml.  

            </trigger>
        4.  Enablement  

            Once rules, transformers, and hooks are loaded, the GrammarManager checks what content should be enabled and enables it. In the case of rules, this means creating instances of all "whitelisted" rules, making grammars for them, and passing those grammars to the GrammarContainer, where they remain until they are disposed of, either because of a rule disable command, or because of a rule enable command which requires a new ccr merge.  

    2.  What the GrammarManager does at run time  

        The task of the GrammarManager is simpler at run time. It basically continues to use the same mechanisms it did at boot time, sans loading. It houses both the "managed rules" (rule class + details) in itself, and the instantiated (rule instance + grammar) combos in its GrammarContainer.  

    3.  The new CCRMerger  

        The new CCRMerger is composable and nearly stateless. It is very important that it stays that way.  

        1.  Composition  

            The new CCRMerger is composed of the TransformersRunner, a rule sorter, a compatibility checker, a merging strategy, and a selfmod rule configurer. Rather than changing the new CCRMerger itself, replacements for these pieces should be optionally swapped in, if possible.  

        2.  Job of the CCRMerger  

            The new CCRMerger is given a collection of "managed rules" (class + details) to merge. Given that, it should return 1+N merge rule instances, where N is the number of merge rules in the collection which have contexts. This is easiest to explain via example.  

            Let's say we pass the CCRMerger rules A, B, C, and D. C has a context for Microsoft Word. D has a context for IntelliJ. In this case, we want three combined rules out of the merge:

            A, B    <--- runs when neither Word nor IntelliJ is in focus
            A, B, C <--- runs when Word is in focus
            A, B, D <--- runs when IntelliJ is in focus

        1.  Reloading complications  

            It used to be the case that an enable/disable command is the only route which could cause a merge of enabled rules. Now it is both enable/disable commands AND file reloads. And this creates a new problem: what if I change TWO rules and then save them? If it were only one at a time, we could just treat it like an enable/disable command and make the edited module the "last-in" rule.  

            As a solution to this, and to generally strengthen the system, the "rule sorter" was introduced to the merger. A rule sorter examines a collection of rules and creates a deterministic order for them. The default rule sorter in 1.0.0 Caster preserves the old "last-in" logic while changing how that works under the hood. By saving the enable/disable order to a config file, Caster can always have a merge order, both when using enable/disable commands, and when a reload causes a merge.  

        2.  The new "5"-Step merge  

            In simple terms, the new merger creates instances of all rules in the enabled set of managed rules, then:
            *   runs all enabled/applicable transformers over all rule instances
            *   sorts the rules
            *   computes compatibility for all rules with each other
            *   creates 1+N merged rules out of the collection, where N=len(contexts)
            *   uses t4ngo's old trick of turning a MappingRule into a RepeatRule on each merged rule
    4.  Design Constraints  

        1.  Rule constructors  

            All rules, ccr and non-ccr must have either an all-defaulted-args or a (preferred) no-args constructor. This is so that the GrammarManager can instantiate them without needing information about constructor parameters.  

        2.  Content modules  

            Starter and user modules need a "get_<type>" function. This is so that the GrammarManager can figure out which modules in the scanned paths are content modules. Each module should only have one of these functions.  

            </type>
        3.  Validations  

            Various validations have been translated out of the old CCRMerger, and a few have been/ will be added. Certain things are now stricter. For example, passing a MergeRule as a non-ccr rule will get that rule rejected.  

        4.  Dependency Injection, Base Classes, and Python 3  

            The 1.0.0 rewrite has made HEAVY use of dependency injection. This minimizes circular import issues and makes unit testing a lot easier. Decreasing the amount of dependency injection is an unacceptable solution to most problems.  

            When Caster is converted to be compatible with Python 3, type hinting will become available and desirable. This should not decrease the amount of dependency injection. Base classes should be used for type hinting rather than implementations. Caster will still work if the D.I. is decreased, but it won't work as well and will get progressively more difficult to maintain.  

4.  General Comments  

    1.  The fate of transformers  

        Some time after filter functions were added to Caster, the Caster user directory was added. This directory was a user-defined location from which user rules and filter functions would be loaded.  

        The creation of the Caster user directory largely denecessited filter functions. If users now had a place to put their custom rules, why create functions to modify existing rules? After all, the process of copying a file out of Caster, changing the pronunciation, and making whatever other modifications were desired was much simpler than learning the filter function API, and just as effective in most cases.  

        There were potential edge cases for filter functions which both the Caster user directory and the new transformers solution do not cover, but since no one ever found those edge cases, nothing is lost by simplifying the system, and in fact, much is gained.  

        The question remains though: if I have the user directory, and its content overrides Caster "starter" content, why do I need transformers? There are some prospective projects in the planning stages which might make use of them, and also, it was the most natural way to preserve words.txt functionality.  

    2.  Suggestions for New Projects  

        1.  Get rid of CasterState and stack.py  

            These are, IMO, the ugliest remaining parts of the old Caster code. A rewrite of these modules is very much in order.  

        2.  settings.SETTINGS  

            The settings.SETTINGS object should be cleaned up to be more OO and less dangerous. There is so much potential for KeyErrors the way it is now.

**Comment by synkarius** [comment] 2019-09-08 03:15
Notes for everyone:
===================
- old custom rules in the user dir will need to have "get_rule" reformatted to new format:
```
def get_rule():
    return MyRule, RuleDetails(name="my rule")
```


Notes for testers:
===================

How to try out the new branch:
1. Back up your .caster directory.
2. Stop Dragon.
3. Uninstall Caster. Either move the files if you have the classic install or use the pip uninstall command if you're on the pip version.
4. Open terminal and navigate to somewhere which is NOT the normal Caster install location. Then:
git clone https://github.com/synkarius/Caster.git
git checkout ccrmerger2
5. Copy the files back to the Natlink user directory, as per the classic install instructions.

Alternatively, if you are pretty slick with Git, you can just set the remote to my fork.

Things that I haven't tested much yet (so please test them!):

- companion rules (formerly MergeRule "non" field) actually activate
- the contexts work well enough for the Git Bash and Jetbrains rules
- all selfmod rules (BringMe, Alias, History, etc.)
- the words.txt transformer, "gdef"
- whatever your most used features were

**Closed** 2019-12-04 20:38 UTC
Labels: High Priority, New Feature, Roadmap
