### ISSUE TITLE
Unable to dictate 5 consecutive numbers

### ISSUE THREAD

**Issue by MarkRx** [dictation-toolbox/Caster#857] opened 2020-10-15 16:39 UTC
**Describe the bug**
When using "numb" I am only able to dictate up to 4 numbers. The 5th one is always chopped off.

This might be an issue with how dragonfly deals with numbers.

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Say "numb one two three four five"
2. Output is 1234

**Expected behavior**
Output is 12345

**System:**
 - OS: Windows 10
 - Program: Any
 - Version: Caster master 3f45fbb0, dragonfly 0.27.1
 - Dictation Engine: Dragon Pro 15

**Comment by kendonB** [comment] 2020-11-08 04:48
@LexiconCode this is a limitation with the dragonfly class that @mrob95 created. I don't think we should address this one in caster, except to properly document the usage. @mrob95 is there potential to modify ShortIntegerRef in dragonfly to allow for longer single-digit utterances?

**Comment by LexiconCode** [comment] 2020-11-24 20:40
Would be best to switch it to IntegerRef.

**Comment by kendonB** [comment] 2020-11-25 09:47
IntegerRef is less general than ShortIntegerRef. ShortIntegerRef is IntegerRef (where you can say "one thousand two hundred and thirty four" with the added feature that you can say "one two three four" for numbers up to 9999

**Comment by LexiconCode** [comment] 2021-01-04 05:16
The following parses free dictation to output a single number. Perhaps this can be used as replacement as it is at least as flexible if not more.

```python
from text_to_num import text2num
from text_to_num import alpha2digit

def words_to_num(numdict):
    text = numdict.replace(r'\number', '') # Remove substring "\number" from DPI formatting
    try:
        #Simple: words to numbers `five hundred sixty three`
        numb = text2num(text, "en") 
        print("text2num:{} ".format(numb)) 
    except ValueError:
        # Reduces complex dictation down to just numerics as a single number
        print("alpha2digit: {}".format(alpha2digit(text, "en")))  #debug
        numb =''.join(re.findall(r"[\d.]", alpha2digit(text, "en")))
        print("numb: {}".format(numb)) #debug
    Text(str(numb)).execute()
```

**Comment by MarkRx** [comment] 2021-01-04 15:18
I can't tell because I don't have `text_to_num `locally. Do these work?

> One zero two three eight

10238

> Ten thousand two hundred thirty eight

10238

> Ten thousand two hundred and thirty eight

10238

> Ten two thirty eight

10238

> One oh two thirty eight dot seven five

10238.75

> One hundred two thirty eight point seventy five

10238.75

> One million two hundred seven thousand eight hundred nintey

1207890

**Comment by LexiconCode** [comment] 2021-01-08 02:18
@MarkRx 
```
1 zero two three eight
numb: 10238
10238
ten thousand two hundred thirty eight
text2num:10238 
10238
ten thousand two hundred  thirty eight
text2num:10238 
10238
ten two thirty eight
numb: 10238
10238
1 zero two thirty eight . seven five
numb: 10238.75
10238.75
1 hundred two thirty eight point seventy five
numb: 110238.75
10238.75
1 million two hundred seven thousand eight hundred ninety
numb: 1207890
1207890
```

The edge cases have been worked out above. It could allow for operators as well.
```
ten thousand + two hundred thirty eight
numb: 10000+238
```
However there are still two edge cases.

- Until I have more control over the CCR process than we presently do it won't work well without some sort of terminal command. For instance if I try to say single digits `num 5+7` yields `5+++++++` which is a part of the punctuation rule. Which produces the + 7 times.
- Since it's parsing free dictation it does have decreased accuracy as the numbers are not weighted as commands. 
 - see the example below where free dictation that's extraneous is stripped out

Extraneous `my cat`
```
1 million two my cat hundred seven thousand eight hundred ninety
numb: 12107890
1207890
```

**Comment by LexiconCode** [comment] 2021-02-08 02:49
@MarkRx @kendonB I have a fix for this in https://github.com/dictation-toolbox/Caster/pull/878 utilizing Dragon's native ShortIntegerRef which allows for greater flexibility than IntegerRef.

**Comment by LexiconCode** [comment] 2021-02-12 18:30
Should be fixed, reopen if there's issues.

**Closed by LexiconCode** 2021-02-12 18:30 UTC
Labels: Bug, Caster Core Spec

**Comment by BawdyInkSlinger** [comment] 2023-09-19 20:33
> The following parses free dictation to output a single number. Perhaps this can be used as replacement as it is at least as flexible if not more for Python 3...
 
> Should be fixed, reopen if there's issues.

Is this only fixed if you use Python 3? I'm using Python 2 and I can still reproduce the issue. The following line is what prints if I say `numb 1 2 3 4 5 6 7 8 9`:

> 1234seven eight nine

The caster status window prints:

> Numbers: [<long>] numb <wnKK>, , 1234
> Navigation: (<capitalization> <spacing> | <capitalization> | <spacing>) [(bow|bowel)] <textnv> [brunt], 6, 0, 6, 0, seven eight

Additional information:

Python 2.7.18
Running DNS/DPI from Dragonfly CLI with Natlink. DPI version 15
My `version.py` file says `__version__ = "1.7.0"`
