### ISSUE TITLE
Enhancements to chain alias and alias command

### ISSUE THREAD

**Issue by mrob95** [dictation-toolbox/caster#358] opened 2018-12-19 22:28 UTC
As far as I can tell, since #245 the alias and chain alias commands both do basically the same thing - create a CCR alias for the highlighted text. Is there any reason not to remove one of them?

**Comment by LexiconCode** [comment] 2018-12-19 23:15
There are two differences with the chain version of the alias command. The first is that you don't have to speak the spec. A box will pop up and ask you for it. The second is that commands created with the chain version will be incorporated into the active CCR set, meaning, they'll be chainable with the other active CCR commands.

**Comment by mrob95** [comment] 2018-12-19 23:21
I've only tested it briefly but they both create chainable commands for me, so the only difference is the input method.

**Comment by LexiconCode** [comment] 2018-12-24 01:32
I can confirm that alias is chainable when it should not. It might be how is added to the nexus https://github.com/synkarius/caster/blob/bc5b2b8bd4a2495c910a4beb4260d50847f922a9/caster/lib/ccr/recording/alias.py#L102

@mrob95 
If the alias commands function as written in the documentation they would have enough utility as separate commands.

Otherwise we could create a single command with a conditional for manual input that uses chain alias GUI. Thoughts?

**Comment by mrob95** [comment] 2018-12-24 01:37
Personally I like the way it works at the moment, I use it for tricky variable/function names which would be a pain to dictate out each time, so I usually want the result to be chainable. I also don't really use the GUI - if you can't create it using a voice command then it's probably not a good alias in the first place. I may be missing some potential use cases though.

**Comment by LexiconCode** [comment] 2018-12-24 04:34
So let me break it down a little bit. 
1. Does the alias commands need to have a chainable and non-chainable version?
2. Does the GUI enhance alias commands functionality?

A few of my use cases were related to commands that aren't suitable for CCR and utilizing the GUI on top of other windows when inputting data. Great for when you're referencing multiple pages of documentation to create a single command/macro/function. 

My thought is to preserve the functionality as it was intended with a few enhancements.

The _alias_ would not be chainable. 
The _chain alias_ would be chainable
Both commands would optional spec parameter to trigger GUI.

You could switch the specs using filter rules. Once https://github.com/synkarius/caster/pull/356 is merge

**Comment by mrob95** [comment] 2018-12-24 14:05
That sounds good, I guess the GUI could be triggered if there is no dictation registered after the command. I'll have a look once the xmas chaos is over :-)

**Comment by LexiconCode** [comment] 2018-12-25 18:35
Great! Perhaps we should update the title to reflect the issue.

**Closed** 2019-01-22 19:34 UTC
Labels: Enhancement
